= Requirements Engineering: User Stories und Epics in Vorgehensmodellen

Belegarbeit im Rahmen des Moduls "Software Engineering"
(https://wse-research.org/team/anbo[Prof. Dr. Andreas Both], Wintersemester 2024/2025 an der https://www.htwk-leipzig.de/[HTWK Leipzig])

== Autoren
- Antonia Swiridoff
- Jonas Pohl
- Mose Schmiedel <mose.schmiedel@stud.htwk-leipzig.de>

== Dateien
- link:01-Requirements-Engineering.pdf[Beleg-PDF]
- link:paper-tex/01-Requirements-Engineering.tex[LaTeX-Quelldatei des Belegs]
- link:paper-tex[Quellverzeichnis für die Beleg-PDF]
- link:presentation[Quellverzeichnis für die Präsentation]

== Abstract
In dieser Arbeit wurde der Einsatz und die Wirkung von Epics und User Stories in der agilen Softwareentwicklung untersucht.
Dazu wurden mithilfe bestehender Literatur drei agile Vorgehensmodelle und die beim Einsatz von Epics und User Stories
auftretenden Herausforderungen betrachtet.
Für die Herausforderungen wurden jeweils mögliche Lösungsvorschläge gefunden, welche anhand von kurzen Beispielen
in dieser Arbeit beschrieben wurden.

Im Verlauf der Recherche sind die Autoren zu dem Schluss gekommen, dass Epics und User Stories ein hilfreiches Werkzeug
für das Requirements Engineering sind. Insbesondere für die agile Softwareentwicklung ist dieses Konzept besser geeignet als traditionelle
Methoden.
